CREATE DATABASE ApparelDB;

CREATE TABLE Users(
    UserID INT IDENTITY(2601,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Username NVARCHAR(50) NOT NULL,
    Password NVARCHAR(50) NOT NULL,
    Department NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100)NOT NULL,
    Phone NVARCHAR(30)NOT NULL,
    DateOfBirth DATE NOT NULL,
    Address NVARCHAR(200) NOT NULL,
    Gender NVARCHAR(20) NOT NULL,
    Role NVARCHAR(50) NOT NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT 'Active'
);

SELECT * FROM Users

Drop TABLE Users
